### ISSUE TITLE
Awesome mod

### ISSUE THREAD

**Issue by MasterSloth1** [tmetcalfe89/JsonifyCraft#23]
just one question, where if the flags section?
![image](https://user-images.githubusercontent.com/34207969/71385455-b688a580-264c-11ea-9174-7839155398f4.png)
https://github.com/tmetcalfe89/JsonifyCraft/wiki/Items

**Comment by tmetcalfe89-zz** [comment]
Glad you're enjoying the mod. Scroll down for the flag section as shown below!
![Screenshot_20191223-184042](https://user-images.githubusercontent.com/3850373/71390125-e0da5480-25b3-11ea-97c3-b94c64371d48.png)

**Comment by MasterSloth1** [comment]
![image](https://user-images.githubusercontent.com/34207969/71395499-0bdbab80-267b-11ea-9fb5-a14edde1f166.png)
i think we are on different pages?

**Comment by MasterSloth1** [comment]
![image](https://user-images.githubusercontent.com/34207969/71395810-74775800-267c-11ea-97f5-17a9cf91e071.png)
i dont think members have access to the page or something

**Comment by tmetcalfe89-zz** [comment]
Oh! I thought you were on blocks. At the moment, flags are a placeholder in items. There are no flags for items yet.

**Comment by MasterSloth1** [comment]
ahhhh thank you lol merry Christmas as well 😄 really liking the mod just one more question when i create new items and blocks the name of the item is really weird lol like
item.jsonifycraft.(itemName here)
im sure your working on fixing that but that is the only bug i have found far good work 😄

**Comment by tmetcalfe89-zz** [comment]
I will add a few basic tutorials when I get back from vacation in a handful of days, but if you look up 1.12 lang files, you'll find the solution to that!
Merry Christmas to you as well!
